## Installation and importing data from source

In [6]:
# pip install ucimlrepo

In [2]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
phishing_websites = fetch_ucirepo(id=327)

# data (as pandas dataframes)
X = phishing_websites.data.features
y = phishing_websites.data.targets

# metadata
print(phishing_websites.metadata)

# variable information
print(phishing_websites.variables)

{'uci_id': 327, 'name': 'Phishing Websites', 'repository_url': 'https://archive.ics.uci.edu/dataset/327/phishing+websites', 'data_url': 'https://archive.ics.uci.edu/static/public/327/data.csv', 'abstract': 'This dataset collected mainly from: PhishTank archive, MillerSmiles archive, Googleâ€™s searching operators.', 'area': 'Computer Science', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 11055, 'num_features': 30, 'feature_types': ['Integer'], 'demographics': [], 'target_col': ['result'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2012, 'last_updated': 'Tue Mar 05 2024', 'dataset_doi': '10.24432/C51W2X', 'creators': ['Rami Mohammad', 'Lee McCluskey'], 'intro_paper': {'ID': 396, 'type': 'NATIVE', 'title': 'An assessment of features related to phishing websites using an automated technique', 'authors': 'R. Mohammad, F. Thabtah, L. Mccluskey', 'venue': 'International Conference for Internet Technology and Secured Transactions', 'year': 2012, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/An-assessment-of-features-related-to-phishing-using-Mohammad-Thabtah/0c0ff58063f4e078714ea74f112bc709ba9fed06', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'One of the challenges faced by our research was the unavailability of reliable training datasets. In fact this challenge faces any researcher in the field. However, although plenty of articles about predicting phishing websites have been disseminated these days, no reliable training dataset has been published publically, may be because there is no agreement in literature on the definitive features that characterize phishing webpages, hence it is difficult to shape a dataset that covers all possible features. \r\nIn this dataset, we shed light on the important features that have proved to be sound and effective in predicting phishing websites. In addition, we propose some new features.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'For Further information about the features see the features file in the data folder.', 'citation': None}}
                          name     role     type demographic description  \
0            having_ip_address  Feature  Integer        None        None
1                   url_length  Feature  Integer        None        None
2           shortining_service  Feature  Integer        None        None
3             having_at_symbol  Feature  Integer        None        None
4     double_slash_redirecting  Feature  Integer        None        None
5                prefix_suffix  Feature  Integer        None        None
6            having_sub_domain  Feature  Integer        None        None
7               sslfinal_state  Feature  Integer        None        None
8   domain_registration_length  Feature  Integer        None        None
9                      favicon  Feature  Integer        None        None
10                        port  Feature  Integer        None        None
11                 https_token  Feature  Integer        None        None
12                 request_url  Feature  Integer        None        None
13               url_of_anchor  Feature  Integer        None        None
14               links_in_tags  Feature  Integer        None        None
15                         sfh  Feature  Integer        None        None
16         submitting_to_email  Feature  Integer        None        None
17                abnormal_url  Feature  Integer        None        None
18                    redirect  Feature  Integer        None        None
19                on_mouseover  Feature  Integer        None        None
20                  rightclick  Feature  Integer        None        None
21                 popupwindow  Feature  Integer        None        None
22                      iframe  Feature  Integer        None        None
23               age_of_domain  Feature  Integer        None        None
24                   dnsrecord  Feature  Integer        None        None
25                 web_traffic  Feature  Integer        None        None
26                   page_rank  Feature  Integer        None        None
27                google_index  Feature  Integer        None        None
28      links_pointing_to_page  Feature  Integer        None        None
29          statistical_report  Feature  Integer        None        None
30                      result   Target  Integer        None        None

   units missing_values
0   None             no
1   None             no
2   None             no
3   None             no
4   None             no
5   None             no
6   None             no
7   None             no
8   None             no
9   None             no
10  None             no
11  None             no
12  None             no
13  None             no
14  None             no
15  None             no
16  None             no
17  None             no
18  None             no
19  None             no
20  None             no
21  None             no
22  None             no
23  None             no
24  None             no
25  None             no
26  None             no
27  None             no
28  None             no
29  None             no
30  None             no

# Imports

In [3]:
import pandas as pd

# Loaded set

In [4]:
X.head()

,having_ip_address,url_length,shortining_service,having_at_symbol,double_slash_redirecting,prefix_suffix,having_sub_domain,sslfinal_state,domain_registration_length,favicon,...,rightclick,popupwindow,iframe,age_of_domain,dnsrecord,web_traffic,page_rank,google_index,links_pointing_to_page,statistical_report
0,-1,1,1,1,-1,-1,-1,-1,-1,1,...,1,1,1,-1,-1,-1,-1,1,1,-1
1,1,1,1,1,1,-1,0,1,-1,1,...,1,1,1,-1,-1,0,-1,1,1,1
2,1,0,1,1,1,-1,-1,-1,-1,1,...,1,1,1,1,-1,1,-1,1,0,-1
3,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,1,-1,-1,1,-1,1,-1,1
4,1,0,-1,1,1,-1,1,1,-1,1,...,1,-1,1,-1,-1,0,-1,1,1,1

In [5]:
y.head()

   result
0      -1
1      -1
2      -1
3      -1
4       1