# Gold Price Prediction
`GLD` - Gold ETF<br>
`SPX` - S&P 500 index<br>
`USO` - oil<br>
`SLV` - silver ETF<br>
`EUR/USD`<br>
<br>
**Years**: 2008-2018, 2290 days

# Imports and loading dataset

In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/Users/gabrielaslomiany/PycharmProjects/Not-So-Small-ML/gold-price-prediction/gold_price_data.csv')
print(df.shape)
df.head()

(2290, 6)

         Date          SPX        GLD        USO     SLV   EUR/USD
0  01/02/2008  1447.160034  84.860001  78.470001  15.180  1.471692
1  01/03/2008  1447.160034  85.570000  78.370003  15.285  1.474491
2  01/04/2008  1411.630005  85.129997  77.309998  15.167  1.475492
3  01/07/2008  1416.180054  84.769997  75.500000  15.053  1.468299
4  01/08/2008  1390.189941  86.779999  76.059998  15.590  1.557099

## Dataset overview

In [6]:
df.describe(include='all')

,Date,SPX,GLD,USO,SLV,EUR/USD
count,2290,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000
unique,2290,NaN,NaN,NaN,NaN,NaN
top,01/02/2008,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,1654.315776,122.732875,31.842221,20.084997,1.283653
std,NaN,519.111540,23.283346,19.523517,7.092566,0.131547
min,NaN,676.530029,70.000000,7.960000,8.850000,1.039047
25%,NaN,1239.874969,109.725000,14.380000,15.570000,1.171313
50%,NaN,1551.434998,120.580002,33.869999,17.268500,1.303297
75%,NaN,2073.010070,132.840004,37.827501,22.882500,1.369971
max,NaN,2872.870117,184.589996,117.480003,47.259998,1.598798

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2290 entries, 0 to 2289
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     2290 non-null   str
 1   SPX      2290 non-null   float64
 2   GLD      2290 non-null   float64
 3   USO      2290 non-null   float64
 4   SLV      2290 non-null   float64
 5   EUR/USD  2290 non-null   float64
dtypes: float64(5), str(1)
memory usage: 107.5 KB

In [11]:
df.duplicated().sum()

np.int64(0)

## Handling Missing Values

In [8]:
df.isna().sum()

Date       0
SPX        0
GLD        0
USO        0
SLV        0
EUR/USD    0
dtype: int64

;) AMAZING